
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.multipiecetools.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.multipiecetools.item.StoneSwordHandleItem;
import net.mcreator.multipiecetools.item.StoneSwordBladeItem;
import net.mcreator.multipiecetools.item.StoneShovelHeadItem;
import net.mcreator.multipiecetools.item.StonePickaxeHeadItem;
import net.mcreator.multipiecetools.item.StoneHoeHeadItem;
import net.mcreator.multipiecetools.item.StoneHandleItem;
import net.mcreator.multipiecetools.item.StoneAxeHeadItem;
import net.mcreator.multipiecetools.item.SHStoneSwordItem;
import net.mcreator.multipiecetools.item.SHStoneShovelItem;
import net.mcreator.multipiecetools.item.SHStonePickaxeItem;
import net.mcreator.multipiecetools.item.SHStoneHoeItem;
import net.mcreator.multipiecetools.item.SHStoneAxeItem;
import net.mcreator.multipiecetools.item.SHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.SHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.SHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.SHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.SHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.SHIronSwordItem;
import net.mcreator.multipiecetools.item.SHIronShovelItem;
import net.mcreator.multipiecetools.item.SHIronPickaxeItem;
import net.mcreator.multipiecetools.item.SHIronHoeItem;
import net.mcreator.multipiecetools.item.SHIronAxeItem;
import net.mcreator.multipiecetools.item.SHGoldenSwordItem;
import net.mcreator.multipiecetools.item.SHGoldenShovelItem;
import net.mcreator.multipiecetools.item.SHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.SHGoldenHoeItem;
import net.mcreator.multipiecetools.item.SHGoldenAxeItem;
import net.mcreator.multipiecetools.item.SHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.SHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.SHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.SHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.SHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.SHDiamondSwordItem;
import net.mcreator.multipiecetools.item.SHDiamondShovelItem;
import net.mcreator.multipiecetools.item.SHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.SHDiamondHoeItem;
import net.mcreator.multipiecetools.item.SHDiamondAxeItem;
import net.mcreator.multipiecetools.item.SHCopperSwordItem;
import net.mcreator.multipiecetools.item.SHCopperShovelItem;
import net.mcreator.multipiecetools.item.SHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.SHCopperHoeItem;
import net.mcreator.multipiecetools.item.SHCopperAxeItem;
import net.mcreator.multipiecetools.item.SHAmethystSwordItem;
import net.mcreator.multipiecetools.item.SHAmethystShovelItem;
import net.mcreator.multipiecetools.item.SHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.SHAmethystHoeItem;
import net.mcreator.multipiecetools.item.SHAmethystAxeItem;
import net.mcreator.multipiecetools.item.NetheriteSwordHandleItem;
import net.mcreator.multipiecetools.item.NetheriteSwordBladeItem;
import net.mcreator.multipiecetools.item.NetheriteShovelHeadItem;
import net.mcreator.multipiecetools.item.NetheritePickaxeHeadItem;
import net.mcreator.multipiecetools.item.NetheriteHoeHeadItem;
import net.mcreator.multipiecetools.item.NetheriteHandleItem;
import net.mcreator.multipiecetools.item.NetheriteAxeHeadItem;
import net.mcreator.multipiecetools.item.NHStoneSwordItem;
import net.mcreator.multipiecetools.item.NHStoneShovelItem;
import net.mcreator.multipiecetools.item.NHStonePickaxeItem;
import net.mcreator.multipiecetools.item.NHStoneHoeItem;
import net.mcreator.multipiecetools.item.NHStoneAxeItem;
import net.mcreator.multipiecetools.item.NHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.NHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.NHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.NHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.NHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.NHIronSwordItem;
import net.mcreator.multipiecetools.item.NHIronShovelItem;
import net.mcreator.multipiecetools.item.NHIronPickaxeItem;
import net.mcreator.multipiecetools.item.NHIronHoeItem;
import net.mcreator.multipiecetools.item.NHIronAxeItem;
import net.mcreator.multipiecetools.item.NHGoldenSwordItem;
import net.mcreator.multipiecetools.item.NHGoldenShovelItem;
import net.mcreator.multipiecetools.item.NHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.NHGoldenHoeItem;
import net.mcreator.multipiecetools.item.NHGoldenAxeItem;
import net.mcreator.multipiecetools.item.NHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.NHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.NHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.NHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.NHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.NHDiamondSwordItem;
import net.mcreator.multipiecetools.item.NHDiamondShovelItem;
import net.mcreator.multipiecetools.item.NHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.NHDiamondHoeItem;
import net.mcreator.multipiecetools.item.NHDiamondAxeItem;
import net.mcreator.multipiecetools.item.NHCopperSwordItem;
import net.mcreator.multipiecetools.item.NHCopperShovelItem;
import net.mcreator.multipiecetools.item.NHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.NHCopperHoeItem;
import net.mcreator.multipiecetools.item.NHCopperAxeItem;
import net.mcreator.multipiecetools.item.NHAmethystSwordItem;
import net.mcreator.multipiecetools.item.NHAmethystShovelItem;
import net.mcreator.multipiecetools.item.NHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.NHAmethystHoeItem;
import net.mcreator.multipiecetools.item.NHAmethystAxeItem;
import net.mcreator.multipiecetools.item.IronSwordHandleItem;
import net.mcreator.multipiecetools.item.IronSwordBladeItem;
import net.mcreator.multipiecetools.item.IronShovelHeadItem;
import net.mcreator.multipiecetools.item.IronPickaxeHeadItem;
import net.mcreator.multipiecetools.item.IronHoeHeadItem;
import net.mcreator.multipiecetools.item.IronHandleItem;
import net.mcreator.multipiecetools.item.IronAxeHeadItem;
import net.mcreator.multipiecetools.item.IHStoneSwordItem;
import net.mcreator.multipiecetools.item.IHStoneShovelItem;
import net.mcreator.multipiecetools.item.IHStonePickaxeItem;
import net.mcreator.multipiecetools.item.IHStoneHoeItem;
import net.mcreator.multipiecetools.item.IHStoneAxeItem;
import net.mcreator.multipiecetools.item.IHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.IHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.IHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.IHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.IHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.IHIronSwordItem;
import net.mcreator.multipiecetools.item.IHIronShovelItem;
import net.mcreator.multipiecetools.item.IHIronPickaxeItem;
import net.mcreator.multipiecetools.item.IHIronHoeItem;
import net.mcreator.multipiecetools.item.IHIronAxeItem;
import net.mcreator.multipiecetools.item.IHGoldenSwordItem;
import net.mcreator.multipiecetools.item.IHGoldenShovelItem;
import net.mcreator.multipiecetools.item.IHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.IHGoldenHoeItem;
import net.mcreator.multipiecetools.item.IHGoldenAxeItem;
import net.mcreator.multipiecetools.item.IHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.IHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.IHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.IHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.IHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.IHDiamondSwordItem;
import net.mcreator.multipiecetools.item.IHDiamondShovelItem;
import net.mcreator.multipiecetools.item.IHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.IHDiamondHoeItem;
import net.mcreator.multipiecetools.item.IHDiamondAxeItem;
import net.mcreator.multipiecetools.item.IHCopperSwordItem;
import net.mcreator.multipiecetools.item.IHCopperShovelItem;
import net.mcreator.multipiecetools.item.IHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.IHCopperHoeItem;
import net.mcreator.multipiecetools.item.IHCopperAxeItem;
import net.mcreator.multipiecetools.item.IHAmethystSwordItem;
import net.mcreator.multipiecetools.item.IHAmethystShovelItem;
import net.mcreator.multipiecetools.item.IHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.IHAmethystHoeItem;
import net.mcreator.multipiecetools.item.IHAmethystAxeItem;
import net.mcreator.multipiecetools.item.GoldSwordHandleItem;
import net.mcreator.multipiecetools.item.GoldSwordBladeItem;
import net.mcreator.multipiecetools.item.GoldShovelHeadItem;
import net.mcreator.multipiecetools.item.GoldPickaxeHeadItem;
import net.mcreator.multipiecetools.item.GoldHoeHeadItem;
import net.mcreator.multipiecetools.item.GoldHandleItem;
import net.mcreator.multipiecetools.item.GoldAxeHeadItem;
import net.mcreator.multipiecetools.item.GHStoneSwordItem;
import net.mcreator.multipiecetools.item.GHStoneShovelItem;
import net.mcreator.multipiecetools.item.GHStonePickaxeItem;
import net.mcreator.multipiecetools.item.GHStoneHoeItem;
import net.mcreator.multipiecetools.item.GHStoneAxeItem;
import net.mcreator.multipiecetools.item.GHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.GHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.GHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.GHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.GHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.GHIronSwordItem;
import net.mcreator.multipiecetools.item.GHIronShovelItem;
import net.mcreator.multipiecetools.item.GHIronPickaxeItem;
import net.mcreator.multipiecetools.item.GHIronHoeItem;
import net.mcreator.multipiecetools.item.GHIronAxeItem;
import net.mcreator.multipiecetools.item.GHGoldenSwordItem;
import net.mcreator.multipiecetools.item.GHGoldenShovelItem;
import net.mcreator.multipiecetools.item.GHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.GHGoldenHoeItem;
import net.mcreator.multipiecetools.item.GHGoldenAxeItem;
import net.mcreator.multipiecetools.item.GHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.GHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.GHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.GHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.GHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.GHDiamondSwordItem;
import net.mcreator.multipiecetools.item.GHDiamondShovelItem;
import net.mcreator.multipiecetools.item.GHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.GHDiamondHoeItem;
import net.mcreator.multipiecetools.item.GHDiamondAxeItem;
import net.mcreator.multipiecetools.item.GHCopperSwordItem;
import net.mcreator.multipiecetools.item.GHCopperShovelItem;
import net.mcreator.multipiecetools.item.GHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.GHCopperHoeItem;
import net.mcreator.multipiecetools.item.GHCopperAxeItem;
import net.mcreator.multipiecetools.item.GHAmethystSwordItem;
import net.mcreator.multipiecetools.item.GHAmethystShovelItem;
import net.mcreator.multipiecetools.item.GHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.GHAmethystHoeItem;
import net.mcreator.multipiecetools.item.GHAmethystAxeItem;
import net.mcreator.multipiecetools.item.EmeraldSwordHandleItem;
import net.mcreator.multipiecetools.item.EmeraldSwordBladeItem;
import net.mcreator.multipiecetools.item.EmeraldShovelHeadItem;
import net.mcreator.multipiecetools.item.EmeraldPickaxeHeadItem;
import net.mcreator.multipiecetools.item.EmeraldHoeHeadItem;
import net.mcreator.multipiecetools.item.EmeraldHandleItem;
import net.mcreator.multipiecetools.item.EmeraldAxeHeadItem;
import net.mcreator.multipiecetools.item.EHStoneSwordItem;
import net.mcreator.multipiecetools.item.EHStoneShovelItem;
import net.mcreator.multipiecetools.item.EHStonePickaxeItem;
import net.mcreator.multipiecetools.item.EHStoneHoeItem;
import net.mcreator.multipiecetools.item.EHStoneAxeItem;
import net.mcreator.multipiecetools.item.EHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.EHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.EHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.EHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.EHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.EHIronSwordItem;
import net.mcreator.multipiecetools.item.EHIronShovelItem;
import net.mcreator.multipiecetools.item.EHIronPickaxeItem;
import net.mcreator.multipiecetools.item.EHIronHoeItem;
import net.mcreator.multipiecetools.item.EHIronAxeItem;
import net.mcreator.multipiecetools.item.EHGoldenSwordItem;
import net.mcreator.multipiecetools.item.EHGoldenShovelItem;
import net.mcreator.multipiecetools.item.EHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.EHGoldenHoeItem;
import net.mcreator.multipiecetools.item.EHGoldenAxeItem;
import net.mcreator.multipiecetools.item.EHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.EHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.EHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.EHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.EHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.EHDiamondSwordItem;
import net.mcreator.multipiecetools.item.EHDiamondShovelItem;
import net.mcreator.multipiecetools.item.EHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.EHDiamondHoeItem;
import net.mcreator.multipiecetools.item.EHDiamondAxeItem;
import net.mcreator.multipiecetools.item.EHCopperSwordItem;
import net.mcreator.multipiecetools.item.EHCopperShovelItem;
import net.mcreator.multipiecetools.item.EHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.EHCopperHoeItem;
import net.mcreator.multipiecetools.item.EHCopperAxeItem;
import net.mcreator.multipiecetools.item.EHAmethystSwordItem;
import net.mcreator.multipiecetools.item.EHAmethystShovelItem;
import net.mcreator.multipiecetools.item.EHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.EHAmethystHoeItem;
import net.mcreator.multipiecetools.item.EHAmethystAxeItem;
import net.mcreator.multipiecetools.item.DiamondSwordHandleItem;
import net.mcreator.multipiecetools.item.DiamondSwordBladeItem;
import net.mcreator.multipiecetools.item.DiamondShovelHeadItem;
import net.mcreator.multipiecetools.item.DiamondPickaxeHeadItem;
import net.mcreator.multipiecetools.item.DiamondHoeHeadItem;
import net.mcreator.multipiecetools.item.DiamondHandleItem;
import net.mcreator.multipiecetools.item.DiamondAxeHeadItem;
import net.mcreator.multipiecetools.item.DHStoneSwordItem;
import net.mcreator.multipiecetools.item.DHStoneShovelItem;
import net.mcreator.multipiecetools.item.DHStonePickaxeItem;
import net.mcreator.multipiecetools.item.DHStoneHoeItem;
import net.mcreator.multipiecetools.item.DHStoneAxeItem;
import net.mcreator.multipiecetools.item.DHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.DHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.DHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.DHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.DHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.DHIronSwordItem;
import net.mcreator.multipiecetools.item.DHIronShovelItem;
import net.mcreator.multipiecetools.item.DHIronPickaxeItem;
import net.mcreator.multipiecetools.item.DHIronHoeItem;
import net.mcreator.multipiecetools.item.DHIronAxeItem;
import net.mcreator.multipiecetools.item.DHGoldenSwordItem;
import net.mcreator.multipiecetools.item.DHGoldenShovelItem;
import net.mcreator.multipiecetools.item.DHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.DHGoldenHoeItem;
import net.mcreator.multipiecetools.item.DHGoldenAxeItem;
import net.mcreator.multipiecetools.item.DHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.DHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.DHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.DHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.DHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.DHDiamondSwordItem;
import net.mcreator.multipiecetools.item.DHDiamondShovelItem;
import net.mcreator.multipiecetools.item.DHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.DHDiamondHoeItem;
import net.mcreator.multipiecetools.item.DHDiamondAxeItem;
import net.mcreator.multipiecetools.item.DHCopperSwordItem;
import net.mcreator.multipiecetools.item.DHCopperShovelItem;
import net.mcreator.multipiecetools.item.DHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.DHCopperHoeItem;
import net.mcreator.multipiecetools.item.DHCopperAxeItem;
import net.mcreator.multipiecetools.item.DHAmethystSwordItem;
import net.mcreator.multipiecetools.item.DHAmethystShovelItem;
import net.mcreator.multipiecetools.item.DHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.DHAmethystHoeItem;
import net.mcreator.multipiecetools.item.DHAmethystAxeItem;
import net.mcreator.multipiecetools.item.CopperSwordHandleItem;
import net.mcreator.multipiecetools.item.CopperSwordBladeItem;
import net.mcreator.multipiecetools.item.CopperShovelHeadItem;
import net.mcreator.multipiecetools.item.CopperPickaxeHeadItem;
import net.mcreator.multipiecetools.item.CopperHoeHeadItem;
import net.mcreator.multipiecetools.item.CopperHandleItem;
import net.mcreator.multipiecetools.item.CopperAxeHeadItem;
import net.mcreator.multipiecetools.item.CHStoneSwordItem;
import net.mcreator.multipiecetools.item.CHStoneShovelItem;
import net.mcreator.multipiecetools.item.CHStonePickaxeItem;
import net.mcreator.multipiecetools.item.CHStoneHoeItem;
import net.mcreator.multipiecetools.item.CHStoneAxeItem;
import net.mcreator.multipiecetools.item.CHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.CHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.CHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.CHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.CHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.CHIronSwordItem;
import net.mcreator.multipiecetools.item.CHIronShovelItem;
import net.mcreator.multipiecetools.item.CHIronPickaxeItem;
import net.mcreator.multipiecetools.item.CHIronHoeItem;
import net.mcreator.multipiecetools.item.CHIronAxeItem;
import net.mcreator.multipiecetools.item.CHGoldenSwordItem;
import net.mcreator.multipiecetools.item.CHGoldenShovelItem;
import net.mcreator.multipiecetools.item.CHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.CHGoldenHoeItem;
import net.mcreator.multipiecetools.item.CHGoldenAxeItem;
import net.mcreator.multipiecetools.item.CHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.CHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.CHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.CHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.CHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.CHDiamondSwordItem;
import net.mcreator.multipiecetools.item.CHDiamondShovelItem;
import net.mcreator.multipiecetools.item.CHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.CHDiamondHoeItem;
import net.mcreator.multipiecetools.item.CHDiamondAxeItem;
import net.mcreator.multipiecetools.item.CHCopperSwordItem;
import net.mcreator.multipiecetools.item.CHCopperShovelItem;
import net.mcreator.multipiecetools.item.CHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.CHCopperHoeItem;
import net.mcreator.multipiecetools.item.CHCopperAxeItem;
import net.mcreator.multipiecetools.item.CHAmethystSwordItem;
import net.mcreator.multipiecetools.item.CHAmethystShovelItem;
import net.mcreator.multipiecetools.item.CHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.CHAmethystHoeItem;
import net.mcreator.multipiecetools.item.CHAmethystAxeItem;
import net.mcreator.multipiecetools.item.AmethystSwordHandleItem;
import net.mcreator.multipiecetools.item.AmethystSwordBladeItem;
import net.mcreator.multipiecetools.item.AmethystShovelHeadItem;
import net.mcreator.multipiecetools.item.AmethystPickaxeHeadItem;
import net.mcreator.multipiecetools.item.AmethystHoeHeadItem;
import net.mcreator.multipiecetools.item.AmethystHandleItem;
import net.mcreator.multipiecetools.item.AmethystAxeHeadItem;
import net.mcreator.multipiecetools.item.AHStoneSwordItem;
import net.mcreator.multipiecetools.item.AHStoneShovelItem;
import net.mcreator.multipiecetools.item.AHStonePickaxeItem;
import net.mcreator.multipiecetools.item.AHStoneHoeItem;
import net.mcreator.multipiecetools.item.AHStoneAxeItem;
import net.mcreator.multipiecetools.item.AHNetheriteSwordItem;
import net.mcreator.multipiecetools.item.AHNetheriteShovelItem;
import net.mcreator.multipiecetools.item.AHNetheritePickaxeItem;
import net.mcreator.multipiecetools.item.AHNetheriteHoeItem;
import net.mcreator.multipiecetools.item.AHNetheriteAxeItem;
import net.mcreator.multipiecetools.item.AHIronSwordItem;
import net.mcreator.multipiecetools.item.AHIronShovelItem;
import net.mcreator.multipiecetools.item.AHIronPickaxeItem;
import net.mcreator.multipiecetools.item.AHIronHoeItem;
import net.mcreator.multipiecetools.item.AHIronAxeItem;
import net.mcreator.multipiecetools.item.AHGoldenSwordItem;
import net.mcreator.multipiecetools.item.AHGoldenShovelItem;
import net.mcreator.multipiecetools.item.AHGoldenPickaxeItem;
import net.mcreator.multipiecetools.item.AHGoldenHoeItem;
import net.mcreator.multipiecetools.item.AHGoldenAxeItem;
import net.mcreator.multipiecetools.item.AHEmeraldSwordItem;
import net.mcreator.multipiecetools.item.AHEmeraldShovelItem;
import net.mcreator.multipiecetools.item.AHEmeraldPickaxeItem;
import net.mcreator.multipiecetools.item.AHEmeraldHoeItem;
import net.mcreator.multipiecetools.item.AHEmeraldAxeItem;
import net.mcreator.multipiecetools.item.AHDiamondSwordItem;
import net.mcreator.multipiecetools.item.AHDiamondShovelItem;
import net.mcreator.multipiecetools.item.AHDiamondPickaxeItem;
import net.mcreator.multipiecetools.item.AHDiamondHoeItem;
import net.mcreator.multipiecetools.item.AHDiamondAxeItem;
import net.mcreator.multipiecetools.item.AHCopperSwordItem;
import net.mcreator.multipiecetools.item.AHCopperShovelItem;
import net.mcreator.multipiecetools.item.AHCopperPickaxeItem;
import net.mcreator.multipiecetools.item.AHCopperHoeItem;
import net.mcreator.multipiecetools.item.AHCopperAxeItem;
import net.mcreator.multipiecetools.item.AHAmethystSwordItem;
import net.mcreator.multipiecetools.item.AHAmethystShovelItem;
import net.mcreator.multipiecetools.item.AHAmethystPickaxeItem;
import net.mcreator.multipiecetools.item.AHAmethystHoeItem;
import net.mcreator.multipiecetools.item.AHAmethystAxeItem;
import net.mcreator.multipiecetools.MultiPieceToolsMod;

public class MultiPieceToolsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MultiPieceToolsMod.MODID);
	public static final RegistryObject<Item> STONE_HANDLE = REGISTRY.register("stone_handle", () -> new StoneHandleItem());
	public static final RegistryObject<Item> IRON_HANDLE = REGISTRY.register("iron_handle", () -> new IronHandleItem());
	public static final RegistryObject<Item> GOLD_HANDLE = REGISTRY.register("gold_handle", () -> new GoldHandleItem());
	public static final RegistryObject<Item> AMETHYST_HANDLE = REGISTRY.register("amethyst_handle", () -> new AmethystHandleItem());
	public static final RegistryObject<Item> DIAMOND_HANDLE = REGISTRY.register("diamond_handle", () -> new DiamondHandleItem());
	public static final RegistryObject<Item> EMERALD_HANDLE = REGISTRY.register("emerald_handle", () -> new EmeraldHandleItem());
	public static final RegistryObject<Item> COPPER_HANDLE = REGISTRY.register("copper_handle", () -> new CopperHandleItem());
	public static final RegistryObject<Item> NETHERITE_HANDLE = REGISTRY.register("netherite_handle", () -> new NetheriteHandleItem());
	public static final RegistryObject<Item> IRON_PICKAXE_HEAD = REGISTRY.register("iron_pickaxe_head", () -> new IronPickaxeHeadItem());
	public static final RegistryObject<Item> STONE_PICKAXE_HEAD = REGISTRY.register("stone_pickaxe_head", () -> new StonePickaxeHeadItem());
	public static final RegistryObject<Item> GOLD_PICKAXE_HEAD = REGISTRY.register("gold_pickaxe_head", () -> new GoldPickaxeHeadItem());
	public static final RegistryObject<Item> AMETHYST_PICKAXE_HEAD = REGISTRY.register("amethyst_pickaxe_head", () -> new AmethystPickaxeHeadItem());
	public static final RegistryObject<Item> DIAMOND_PICKAXE_HEAD = REGISTRY.register("diamond_pickaxe_head", () -> new DiamondPickaxeHeadItem());
	public static final RegistryObject<Item> EMERALD_PICKAXE_HEAD = REGISTRY.register("emerald_pickaxe_head", () -> new EmeraldPickaxeHeadItem());
	public static final RegistryObject<Item> COPPER_PICKAXE_HEAD = REGISTRY.register("copper_pickaxe_head", () -> new CopperPickaxeHeadItem());
	public static final RegistryObject<Item> NETHERITE_PICKAXE_HEAD = REGISTRY.register("netherite_pickaxe_head", () -> new NetheritePickaxeHeadItem());
	public static final RegistryObject<Item> IRON_AXE_HEAD = REGISTRY.register("iron_axe_head", () -> new IronAxeHeadItem());
	public static final RegistryObject<Item> STONE_AXE_HEAD = REGISTRY.register("stone_axe_head", () -> new StoneAxeHeadItem());
	public static final RegistryObject<Item> GOLD_AXE_HEAD = REGISTRY.register("gold_axe_head", () -> new GoldAxeHeadItem());
	public static final RegistryObject<Item> AMETHYST_AXE_HEAD = REGISTRY.register("amethyst_axe_head", () -> new AmethystAxeHeadItem());
	public static final RegistryObject<Item> DIAMOND_AXE_HEAD = REGISTRY.register("diamond_axe_head", () -> new DiamondAxeHeadItem());
	public static final RegistryObject<Item> EMERALD_AXE_HEAD = REGISTRY.register("emerald_axe_head", () -> new EmeraldAxeHeadItem());
	public static final RegistryObject<Item> COPPER_AXE_HEAD = REGISTRY.register("copper_axe_head", () -> new CopperAxeHeadItem());
	public static final RegistryObject<Item> NETHERITE_AXE_HEAD = REGISTRY.register("netherite_axe_head", () -> new NetheriteAxeHeadItem());
	public static final RegistryObject<Item> IRON_SHOVEL_HEAD = REGISTRY.register("iron_shovel_head", () -> new IronShovelHeadItem());
	public static final RegistryObject<Item> STONE_SHOVEL_HEAD = REGISTRY.register("stone_shovel_head", () -> new StoneShovelHeadItem());
	public static final RegistryObject<Item> GOLD_SHOVEL_HEAD = REGISTRY.register("gold_shovel_head", () -> new GoldShovelHeadItem());
	public static final RegistryObject<Item> AMETHYST_SHOVEL_HEAD = REGISTRY.register("amethyst_shovel_head", () -> new AmethystShovelHeadItem());
	public static final RegistryObject<Item> DIAMOND_SHOVEL_HEAD = REGISTRY.register("diamond_shovel_head", () -> new DiamondShovelHeadItem());
	public static final RegistryObject<Item> EMERALD_SHOVEL_HEAD = REGISTRY.register("emerald_shovel_head", () -> new EmeraldShovelHeadItem());
	public static final RegistryObject<Item> COPPER_SHOVEL_HEAD = REGISTRY.register("copper_shovel_head", () -> new CopperShovelHeadItem());
	public static final RegistryObject<Item> NETHERITE_SHOVEL_HEAD = REGISTRY.register("netherite_shovel_head", () -> new NetheriteShovelHeadItem());
	public static final RegistryObject<Item> IRON_HOE_HEAD = REGISTRY.register("iron_hoe_head", () -> new IronHoeHeadItem());
	public static final RegistryObject<Item> STONE_HOE_HEAD = REGISTRY.register("stone_hoe_head", () -> new StoneHoeHeadItem());
	public static final RegistryObject<Item> GOLD_HOE_HEAD = REGISTRY.register("gold_hoe_head", () -> new GoldHoeHeadItem());
	public static final RegistryObject<Item> AMETHYST_HOE_HEAD = REGISTRY.register("amethyst_hoe_head", () -> new AmethystHoeHeadItem());
	public static final RegistryObject<Item> DIAMOND_HOE_HEAD = REGISTRY.register("diamond_hoe_head", () -> new DiamondHoeHeadItem());
	public static final RegistryObject<Item> EMERALD_HOE_HEAD = REGISTRY.register("emerald_hoe_head", () -> new EmeraldHoeHeadItem());
	public static final RegistryObject<Item> COPPER_HOE_HEAD = REGISTRY.register("copper_hoe_head", () -> new CopperHoeHeadItem());
	public static final RegistryObject<Item> NETHERITE_HOE_HEAD = REGISTRY.register("netherite_hoe_head", () -> new NetheriteHoeHeadItem());
	public static final RegistryObject<Item> IRON_SWORD_BLADE = REGISTRY.register("iron_sword_blade", () -> new IronSwordBladeItem());
	public static final RegistryObject<Item> STONE_SWORD_BLADE = REGISTRY.register("stone_sword_blade", () -> new StoneSwordBladeItem());
	public static final RegistryObject<Item> GOLD_SWORD_BLADE = REGISTRY.register("gold_sword_blade", () -> new GoldSwordBladeItem());
	public static final RegistryObject<Item> AMETHYST_SWORD_BLADE = REGISTRY.register("amethyst_sword_blade", () -> new AmethystSwordBladeItem());
	public static final RegistryObject<Item> DIAMOND_SWORD_BLADE = REGISTRY.register("diamond_sword_blade", () -> new DiamondSwordBladeItem());
	public static final RegistryObject<Item> EMERALD_SWORD_BLADE = REGISTRY.register("emerald_sword_blade", () -> new EmeraldSwordBladeItem());
	public static final RegistryObject<Item> COPPER_SWORD_BLADE = REGISTRY.register("copper_sword_blade", () -> new CopperSwordBladeItem());
	public static final RegistryObject<Item> NETHERITE_SWORD_BLADE = REGISTRY.register("netherite_sword_blade", () -> new NetheriteSwordBladeItem());
	public static final RegistryObject<Item> IRON_SWORD_HANDLE = REGISTRY.register("iron_sword_handle", () -> new IronSwordHandleItem());
	public static final RegistryObject<Item> STONE_SWORD_HANDLE = REGISTRY.register("stone_sword_handle", () -> new StoneSwordHandleItem());
	public static final RegistryObject<Item> GOLD_SWORD_HANDLE = REGISTRY.register("gold_sword_handle", () -> new GoldSwordHandleItem());
	public static final RegistryObject<Item> AMETHYST_SWORD_HANDLE = REGISTRY.register("amethyst_sword_handle", () -> new AmethystSwordHandleItem());
	public static final RegistryObject<Item> DIAMOND_SWORD_HANDLE = REGISTRY.register("diamond_sword_handle", () -> new DiamondSwordHandleItem());
	public static final RegistryObject<Item> EMERALD_SWORD_HANDLE = REGISTRY.register("emerald_sword_handle", () -> new EmeraldSwordHandleItem());
	public static final RegistryObject<Item> COPPER_SWORD_HANDLE = REGISTRY.register("copper_sword_handle", () -> new CopperSwordHandleItem());
	public static final RegistryObject<Item> NETHERITE_SWORD_HANDLE = REGISTRY.register("netherite_sword_handle", () -> new NetheriteSwordHandleItem());
	public static final RegistryObject<Item> IH_IRON_PICKAXE = REGISTRY.register("ih_iron_pickaxe", () -> new IHIronPickaxeItem());
	public static final RegistryObject<Item> SH_IRON_PICKAXE = REGISTRY.register("sh_iron_pickaxe", () -> new SHIronPickaxeItem());
	public static final RegistryObject<Item> GH_IRON_PICKAXE = REGISTRY.register("gh_iron_pickaxe", () -> new GHIronPickaxeItem());
	public static final RegistryObject<Item> AH_IRON_PICKAXE = REGISTRY.register("ah_iron_pickaxe", () -> new AHIronPickaxeItem());
	public static final RegistryObject<Item> DH_IRON_PICKAXE = REGISTRY.register("dh_iron_pickaxe", () -> new DHIronPickaxeItem());
	public static final RegistryObject<Item> EH_IRON_PICKAXE = REGISTRY.register("eh_iron_pickaxe", () -> new EHIronPickaxeItem());
	public static final RegistryObject<Item> CH_IRON_PICKAXE = REGISTRY.register("ch_iron_pickaxe", () -> new CHIronPickaxeItem());
	public static final RegistryObject<Item> NH_IRON_PICKAXE = REGISTRY.register("nh_iron_pickaxe", () -> new NHIronPickaxeItem());
	public static final RegistryObject<Item> IH_IRON_AXE = REGISTRY.register("ih_iron_axe", () -> new IHIronAxeItem());
	public static final RegistryObject<Item> SH_IRON_AXE = REGISTRY.register("sh_iron_axe", () -> new SHIronAxeItem());
	public static final RegistryObject<Item> GH_IRON_AXE = REGISTRY.register("gh_iron_axe", () -> new GHIronAxeItem());
	public static final RegistryObject<Item> AH_IRON_AXE = REGISTRY.register("ah_iron_axe", () -> new AHIronAxeItem());
	public static final RegistryObject<Item> DH_IRON_AXE = REGISTRY.register("dh_iron_axe", () -> new DHIronAxeItem());
	public static final RegistryObject<Item> EH_IRON_AXE = REGISTRY.register("eh_iron_axe", () -> new EHIronAxeItem());
	public static final RegistryObject<Item> CH_IRON_AXE = REGISTRY.register("ch_iron_axe", () -> new CHIronAxeItem());
	public static final RegistryObject<Item> NH_IRON_AXE = REGISTRY.register("nh_iron_axe", () -> new NHIronAxeItem());
	public static final RegistryObject<Item> IH_IRON_SHOVEL = REGISTRY.register("ih_iron_shovel", () -> new IHIronShovelItem());
	public static final RegistryObject<Item> SH_IRON_SHOVEL = REGISTRY.register("sh_iron_shovel", () -> new SHIronShovelItem());
	public static final RegistryObject<Item> GH_IRON_SHOVEL = REGISTRY.register("gh_iron_shovel", () -> new GHIronShovelItem());
	public static final RegistryObject<Item> AH_IRON_SHOVEL = REGISTRY.register("ah_iron_shovel", () -> new AHIronShovelItem());
	public static final RegistryObject<Item> DH_IRON_SHOVEL = REGISTRY.register("dh_iron_shovel", () -> new DHIronShovelItem());
	public static final RegistryObject<Item> EH_IRON_SHOVEL = REGISTRY.register("eh_iron_shovel", () -> new EHIronShovelItem());
	public static final RegistryObject<Item> CH_IRON_SHOVEL = REGISTRY.register("ch_iron_shovel", () -> new CHIronShovelItem());
	public static final RegistryObject<Item> NH_IRON_SHOVEL = REGISTRY.register("nh_iron_shovel", () -> new NHIronShovelItem());
	public static final RegistryObject<Item> IH_IRON_HOE = REGISTRY.register("ih_iron_hoe", () -> new IHIronHoeItem());
	public static final RegistryObject<Item> SH_IRON_HOE = REGISTRY.register("sh_iron_hoe", () -> new SHIronHoeItem());
	public static final RegistryObject<Item> GH_IRON_HOE = REGISTRY.register("gh_iron_hoe", () -> new GHIronHoeItem());
	public static final RegistryObject<Item> AH_IRON_HOE = REGISTRY.register("ah_iron_hoe", () -> new AHIronHoeItem());
	public static final RegistryObject<Item> DH_IRON_HOE = REGISTRY.register("dh_iron_hoe", () -> new DHIronHoeItem());
	public static final RegistryObject<Item> EH_IRON_HOE = REGISTRY.register("eh_iron_hoe", () -> new EHIronHoeItem());
	public static final RegistryObject<Item> CH_IRON_HOE = REGISTRY.register("ch_iron_hoe", () -> new CHIronHoeItem());
	public static final RegistryObject<Item> NH_IRON_HOE = REGISTRY.register("nh_iron_hoe", () -> new NHIronHoeItem());
	public static final RegistryObject<Item> IH_IRON_SWORD = REGISTRY.register("ih_iron_sword", () -> new IHIronSwordItem());
	public static final RegistryObject<Item> SH_IRON_SWORD = REGISTRY.register("sh_iron_sword", () -> new SHIronSwordItem());
	public static final RegistryObject<Item> GH_IRON_SWORD = REGISTRY.register("gh_iron_sword", () -> new GHIronSwordItem());
	public static final RegistryObject<Item> AH_IRON_SWORD = REGISTRY.register("ah_iron_sword", () -> new AHIronSwordItem());
	public static final RegistryObject<Item> DH_IRON_SWORD = REGISTRY.register("dh_iron_sword", () -> new DHIronSwordItem());
	public static final RegistryObject<Item> EH_IRON_SWORD = REGISTRY.register("eh_iron_sword", () -> new EHIronSwordItem());
	public static final RegistryObject<Item> CH_IRON_SWORD = REGISTRY.register("ch_iron_sword", () -> new CHIronSwordItem());
	public static final RegistryObject<Item> NH_IRON_SWORD = REGISTRY.register("nh_iron_sword", () -> new NHIronSwordItem());
	public static final RegistryObject<Item> IH_STONE_PICKAXE = REGISTRY.register("ih_stone_pickaxe", () -> new IHStonePickaxeItem());
	public static final RegistryObject<Item> SH_STONE_PICKAXE = REGISTRY.register("sh_stone_pickaxe", () -> new SHStonePickaxeItem());
	public static final RegistryObject<Item> GH_STONE_PICKAXE = REGISTRY.register("gh_stone_pickaxe", () -> new GHStonePickaxeItem());
	public static final RegistryObject<Item> AH_STONE_PICKAXE = REGISTRY.register("ah_stone_pickaxe", () -> new AHStonePickaxeItem());
	public static final RegistryObject<Item> DH_STONE_PICKAXE = REGISTRY.register("dh_stone_pickaxe", () -> new DHStonePickaxeItem());
	public static final RegistryObject<Item> EH_STONE_PICKAXE = REGISTRY.register("eh_stone_pickaxe", () -> new EHStonePickaxeItem());
	public static final RegistryObject<Item> CH_STONE_PICKAXE = REGISTRY.register("ch_stone_pickaxe", () -> new CHStonePickaxeItem());
	public static final RegistryObject<Item> NH_STONE_PICKAXE = REGISTRY.register("nh_stone_pickaxe", () -> new NHStonePickaxeItem());
	public static final RegistryObject<Item> IH_STONE_AXE = REGISTRY.register("ih_stone_axe", () -> new IHStoneAxeItem());
	public static final RegistryObject<Item> SH_STONE_AXE = REGISTRY.register("sh_stone_axe", () -> new SHStoneAxeItem());
	public static final RegistryObject<Item> GH_STONE_AXE = REGISTRY.register("gh_stone_axe", () -> new GHStoneAxeItem());
	public static final RegistryObject<Item> AH_STONE_AXE = REGISTRY.register("ah_stone_axe", () -> new AHStoneAxeItem());
	public static final RegistryObject<Item> DH_STONE_AXE = REGISTRY.register("dh_stone_axe", () -> new DHStoneAxeItem());
	public static final RegistryObject<Item> EH_STONE_AXE = REGISTRY.register("eh_stone_axe", () -> new EHStoneAxeItem());
	public static final RegistryObject<Item> CH_STONE_AXE = REGISTRY.register("ch_stone_axe", () -> new CHStoneAxeItem());
	public static final RegistryObject<Item> NH_STONE_AXE = REGISTRY.register("nh_stone_axe", () -> new NHStoneAxeItem());
	public static final RegistryObject<Item> IH_STONE_SHOVEL = REGISTRY.register("ih_stone_shovel", () -> new IHStoneShovelItem());
	public static final RegistryObject<Item> SH_STONE_SHOVEL = REGISTRY.register("sh_stone_shovel", () -> new SHStoneShovelItem());
	public static final RegistryObject<Item> GH_STONE_SHOVEL = REGISTRY.register("gh_stone_shovel", () -> new GHStoneShovelItem());
	public static final RegistryObject<Item> AH_STONE_SHOVEL = REGISTRY.register("ah_stone_shovel", () -> new AHStoneShovelItem());
	public static final RegistryObject<Item> DH_STONE_SHOVEL = REGISTRY.register("dh_stone_shovel", () -> new DHStoneShovelItem());
	public static final RegistryObject<Item> EH_STONE_SHOVEL = REGISTRY.register("eh_stone_shovel", () -> new EHStoneShovelItem());
	public static final RegistryObject<Item> CH_STONE_SHOVEL = REGISTRY.register("ch_stone_shovel", () -> new CHStoneShovelItem());
	public static final RegistryObject<Item> NH_STONE_SHOVEL = REGISTRY.register("nh_stone_shovel", () -> new NHStoneShovelItem());
	public static final RegistryObject<Item> IH_STONE_HOE = REGISTRY.register("ih_stone_hoe", () -> new IHStoneHoeItem());
	public static final RegistryObject<Item> SH_STONE_HOE = REGISTRY.register("sh_stone_hoe", () -> new SHStoneHoeItem());
	public static final RegistryObject<Item> GH_STONE_HOE = REGISTRY.register("gh_stone_hoe", () -> new GHStoneHoeItem());
	public static final RegistryObject<Item> AH_STONE_HOE = REGISTRY.register("ah_stone_hoe", () -> new AHStoneHoeItem());
	public static final RegistryObject<Item> DH_STONE_HOE = REGISTRY.register("dh_stone_hoe", () -> new DHStoneHoeItem());
	public static final RegistryObject<Item> EH_STONE_HOE = REGISTRY.register("eh_stone_hoe", () -> new EHStoneHoeItem());
	public static final RegistryObject<Item> CH_STONE_HOE = REGISTRY.register("ch_stone_hoe", () -> new CHStoneHoeItem());
	public static final RegistryObject<Item> NH_STONE_HOE = REGISTRY.register("nh_stone_hoe", () -> new NHStoneHoeItem());
	public static final RegistryObject<Item> IH_STONE_SWORD = REGISTRY.register("ih_stone_sword", () -> new IHStoneSwordItem());
	public static final RegistryObject<Item> SH_STONE_SWORD = REGISTRY.register("sh_stone_sword", () -> new SHStoneSwordItem());
	public static final RegistryObject<Item> GH_STONE_SWORD = REGISTRY.register("gh_stone_sword", () -> new GHStoneSwordItem());
	public static final RegistryObject<Item> AH_STONE_SWORD = REGISTRY.register("ah_stone_sword", () -> new AHStoneSwordItem());
	public static final RegistryObject<Item> DH_STONE_SWORD = REGISTRY.register("dh_stone_sword", () -> new DHStoneSwordItem());
	public static final RegistryObject<Item> EH_STONE_SWORD = REGISTRY.register("eh_stone_sword", () -> new EHStoneSwordItem());
	public static final RegistryObject<Item> CH_STONE_SWORD = REGISTRY.register("ch_stone_sword", () -> new CHStoneSwordItem());
	public static final RegistryObject<Item> NH_STONE_SWORD = REGISTRY.register("nh_stone_sword", () -> new NHStoneSwordItem());
	public static final RegistryObject<Item> IH_GOLDEN_PICKAXE = REGISTRY.register("ih_golden_pickaxe", () -> new IHGoldenPickaxeItem());
	public static final RegistryObject<Item> SH_GOLDEN_PICKAXE = REGISTRY.register("sh_golden_pickaxe", () -> new SHGoldenPickaxeItem());
	public static final RegistryObject<Item> GH_GOLDEN_PICKAXE = REGISTRY.register("gh_golden_pickaxe", () -> new GHGoldenPickaxeItem());
	public static final RegistryObject<Item> AH_GOLDEN_PICKAXE = REGISTRY.register("ah_golden_pickaxe", () -> new AHGoldenPickaxeItem());
	public static final RegistryObject<Item> DH_GOLDEN_PICKAXE = REGISTRY.register("dh_golden_pickaxe", () -> new DHGoldenPickaxeItem());
	public static final RegistryObject<Item> EH_GOLDEN_PICKAXE = REGISTRY.register("eh_golden_pickaxe", () -> new EHGoldenPickaxeItem());
	public static final RegistryObject<Item> CH_GOLDEN_PICKAXE = REGISTRY.register("ch_golden_pickaxe", () -> new CHGoldenPickaxeItem());
	public static final RegistryObject<Item> NH_GOLDEN_PICKAXE = REGISTRY.register("nh_golden_pickaxe", () -> new NHGoldenPickaxeItem());
	public static final RegistryObject<Item> IH_GOLDEN_AXE = REGISTRY.register("ih_golden_axe", () -> new IHGoldenAxeItem());
	public static final RegistryObject<Item> SH_GOLDEN_AXE = REGISTRY.register("sh_golden_axe", () -> new SHGoldenAxeItem());
	public static final RegistryObject<Item> GH_GOLDEN_AXE = REGISTRY.register("gh_golden_axe", () -> new GHGoldenAxeItem());
	public static final RegistryObject<Item> AH_GOLDEN_AXE = REGISTRY.register("ah_golden_axe", () -> new AHGoldenAxeItem());
	public static final RegistryObject<Item> DH_GOLDEN_AXE = REGISTRY.register("dh_golden_axe", () -> new DHGoldenAxeItem());
	public static final RegistryObject<Item> EH_GOLDEN_AXE = REGISTRY.register("eh_golden_axe", () -> new EHGoldenAxeItem());
	public static final RegistryObject<Item> CH_GOLDEN_AXE = REGISTRY.register("ch_golden_axe", () -> new CHGoldenAxeItem());
	public static final RegistryObject<Item> NH_GOLDEN_AXE = REGISTRY.register("nh_golden_axe", () -> new NHGoldenAxeItem());
	public static final RegistryObject<Item> IH_GOLDEN_SHOVEL = REGISTRY.register("ih_golden_shovel", () -> new IHGoldenShovelItem());
	public static final RegistryObject<Item> SH_GOLDEN_SHOVEL = REGISTRY.register("sh_golden_shovel", () -> new SHGoldenShovelItem());
	public static final RegistryObject<Item> GH_GOLDEN_SHOVEL = REGISTRY.register("gh_golden_shovel", () -> new GHGoldenShovelItem());
	public static final RegistryObject<Item> AH_GOLDEN_SHOVEL = REGISTRY.register("ah_golden_shovel", () -> new AHGoldenShovelItem());
	public static final RegistryObject<Item> DH_GOLDEN_SHOVEL = REGISTRY.register("dh_golden_shovel", () -> new DHGoldenShovelItem());
	public static final RegistryObject<Item> EH_GOLDEN_SHOVEL = REGISTRY.register("eh_golden_shovel", () -> new EHGoldenShovelItem());
	public static final RegistryObject<Item> CH_GOLDEN_SHOVEL = REGISTRY.register("ch_golden_shovel", () -> new CHGoldenShovelItem());
	public static final RegistryObject<Item> NH_GOLDEN_SHOVEL = REGISTRY.register("nh_golden_shovel", () -> new NHGoldenShovelItem());
	public static final RegistryObject<Item> IH_GOLDEN_HOE = REGISTRY.register("ih_golden_hoe", () -> new IHGoldenHoeItem());
	public static final RegistryObject<Item> SH_GOLDEN_HOE = REGISTRY.register("sh_golden_hoe", () -> new SHGoldenHoeItem());
	public static final RegistryObject<Item> GH_GOLDEN_HOE = REGISTRY.register("gh_golden_hoe", () -> new GHGoldenHoeItem());
	public static final RegistryObject<Item> AH_GOLDEN_HOE = REGISTRY.register("ah_golden_hoe", () -> new AHGoldenHoeItem());
	public static final RegistryObject<Item> DH_GOLDEN_HOE = REGISTRY.register("dh_golden_hoe", () -> new DHGoldenHoeItem());
	public static final RegistryObject<Item> EH_GOLDEN_HOE = REGISTRY.register("eh_golden_hoe", () -> new EHGoldenHoeItem());
	public static final RegistryObject<Item> CH_GOLDEN_HOE = REGISTRY.register("ch_golden_hoe", () -> new CHGoldenHoeItem());
	public static final RegistryObject<Item> NH_GOLDEN_HOE = REGISTRY.register("nh_golden_hoe", () -> new NHGoldenHoeItem());
	public static final RegistryObject<Item> IH_GOLDEN_SWORD = REGISTRY.register("ih_golden_sword", () -> new IHGoldenSwordItem());
	public static final RegistryObject<Item> SH_GOLDEN_SWORD = REGISTRY.register("sh_golden_sword", () -> new SHGoldenSwordItem());
	public static final RegistryObject<Item> GH_GOLDEN_SWORD = REGISTRY.register("gh_golden_sword", () -> new GHGoldenSwordItem());
	public static final RegistryObject<Item> AH_GOLDEN_SWORD = REGISTRY.register("ah_golden_sword", () -> new AHGoldenSwordItem());
	public static final RegistryObject<Item> DH_GOLDEN_SWORD = REGISTRY.register("dh_golden_sword", () -> new DHGoldenSwordItem());
	public static final RegistryObject<Item> EH_GOLDEN_SWORD = REGISTRY.register("eh_golden_sword", () -> new EHGoldenSwordItem());
	public static final RegistryObject<Item> CH_GOLDEN_SWORD = REGISTRY.register("ch_golden_sword", () -> new CHGoldenSwordItem());
	public static final RegistryObject<Item> NH_GOLDEN_SWORD = REGISTRY.register("nh_golden_sword", () -> new NHGoldenSwordItem());
	public static final RegistryObject<Item> IH_AMETHYST_PICKAXE = REGISTRY.register("ih_amethyst_pickaxe", () -> new IHAmethystPickaxeItem());
	public static final RegistryObject<Item> SH_AMETHYST_PICKAXE = REGISTRY.register("sh_amethyst_pickaxe", () -> new SHAmethystPickaxeItem());
	public static final RegistryObject<Item> GH_AMETHYST_PICKAXE = REGISTRY.register("gh_amethyst_pickaxe", () -> new GHAmethystPickaxeItem());
	public static final RegistryObject<Item> AH_AMETHYST_PICKAXE = REGISTRY.register("ah_amethyst_pickaxe", () -> new AHAmethystPickaxeItem());
	public static final RegistryObject<Item> DH_AMETHYST_PICKAXE = REGISTRY.register("dh_amethyst_pickaxe", () -> new DHAmethystPickaxeItem());
	public static final RegistryObject<Item> EH_AMETHYST_PICKAXE = REGISTRY.register("eh_amethyst_pickaxe", () -> new EHAmethystPickaxeItem());
	public static final RegistryObject<Item> CH_AMETHYST_PICKAXE = REGISTRY.register("ch_amethyst_pickaxe", () -> new CHAmethystPickaxeItem());
	public static final RegistryObject<Item> NH_AMETHYST_PICKAXE = REGISTRY.register("nh_amethyst_pickaxe", () -> new NHAmethystPickaxeItem());
	public static final RegistryObject<Item> IH_AMETHYST_AXE = REGISTRY.register("ih_amethyst_axe", () -> new IHAmethystAxeItem());
	public static final RegistryObject<Item> SH_AMETHYST_AXE = REGISTRY.register("sh_amethyst_axe", () -> new SHAmethystAxeItem());
	public static final RegistryObject<Item> GH_AMETHYST_AXE = REGISTRY.register("gh_amethyst_axe", () -> new GHAmethystAxeItem());
	public static final RegistryObject<Item> AH_AMETHYST_AXE = REGISTRY.register("ah_amethyst_axe", () -> new AHAmethystAxeItem());
	public static final RegistryObject<Item> DH_AMETHYST_AXE = REGISTRY.register("dh_amethyst_axe", () -> new DHAmethystAxeItem());
	public static final RegistryObject<Item> EH_AMETHYST_AXE = REGISTRY.register("eh_amethyst_axe", () -> new EHAmethystAxeItem());
	public static final RegistryObject<Item> CH_AMETHYST_AXE = REGISTRY.register("ch_amethyst_axe", () -> new CHAmethystAxeItem());
	public static final RegistryObject<Item> NH_AMETHYST_AXE = REGISTRY.register("nh_amethyst_axe", () -> new NHAmethystAxeItem());
	public static final RegistryObject<Item> IH_AMETHYST_SHOVEL = REGISTRY.register("ih_amethyst_shovel", () -> new IHAmethystShovelItem());
	public static final RegistryObject<Item> SH_AMETHYST_SHOVEL = REGISTRY.register("sh_amethyst_shovel", () -> new SHAmethystShovelItem());
	public static final RegistryObject<Item> GH_AMETHYST_SHOVEL = REGISTRY.register("gh_amethyst_shovel", () -> new GHAmethystShovelItem());
	public static final RegistryObject<Item> AH_AMETHYST_SHOVEL = REGISTRY.register("ah_amethyst_shovel", () -> new AHAmethystShovelItem());
	public static final RegistryObject<Item> DH_AMETHYST_SHOVEL = REGISTRY.register("dh_amethyst_shovel", () -> new DHAmethystShovelItem());
	public static final RegistryObject<Item> EH_AMETHYST_SHOVEL = REGISTRY.register("eh_amethyst_shovel", () -> new EHAmethystShovelItem());
	public static final RegistryObject<Item> CH_AMETHYST_SHOVEL = REGISTRY.register("ch_amethyst_shovel", () -> new CHAmethystShovelItem());
	public static final RegistryObject<Item> NH_AMETHYST_SHOVEL = REGISTRY.register("nh_amethyst_shovel", () -> new NHAmethystShovelItem());
	public static final RegistryObject<Item> IH_AMETHYST_HOE = REGISTRY.register("ih_amethyst_hoe", () -> new IHAmethystHoeItem());
	public static final RegistryObject<Item> SH_AMETHYST_HOE = REGISTRY.register("sh_amethyst_hoe", () -> new SHAmethystHoeItem());
	public static final RegistryObject<Item> GH_AMETHYST_HOE = REGISTRY.register("gh_amethyst_hoe", () -> new GHAmethystHoeItem());
	public static final RegistryObject<Item> AH_AMETHYST_HOE = REGISTRY.register("ah_amethyst_hoe", () -> new AHAmethystHoeItem());
	public static final RegistryObject<Item> DH_AMETHYST_HOE = REGISTRY.register("dh_amethyst_hoe", () -> new DHAmethystHoeItem());
	public static final RegistryObject<Item> EH_AMETHYST_HOE = REGISTRY.register("eh_amethyst_hoe", () -> new EHAmethystHoeItem());
	public static final RegistryObject<Item> CH_AMETHYST_HOE = REGISTRY.register("ch_amethyst_hoe", () -> new CHAmethystHoeItem());
	public static final RegistryObject<Item> NH_AMETHYST_HOE = REGISTRY.register("nh_amethyst_hoe", () -> new NHAmethystHoeItem());
	public static final RegistryObject<Item> IH_AMETHYST_SWORD = REGISTRY.register("ih_amethyst_sword", () -> new IHAmethystSwordItem());
	public static final RegistryObject<Item> SH_AMETHYST_SWORD = REGISTRY.register("sh_amethyst_sword", () -> new SHAmethystSwordItem());
	public static final RegistryObject<Item> GH_AMETHYST_SWORD = REGISTRY.register("gh_amethyst_sword", () -> new GHAmethystSwordItem());
	public static final RegistryObject<Item> AH_AMETHYST_SWORD = REGISTRY.register("ah_amethyst_sword", () -> new AHAmethystSwordItem());
	public static final RegistryObject<Item> DH_AMETHYST_SWORD = REGISTRY.register("dh_amethyst_sword", () -> new DHAmethystSwordItem());
	public static final RegistryObject<Item> EH_AMETHYST_SWORD = REGISTRY.register("eh_amethyst_sword", () -> new EHAmethystSwordItem());
	public static final RegistryObject<Item> CH_AMETHYST_SWORD = REGISTRY.register("ch_amethyst_sword", () -> new CHAmethystSwordItem());
	public static final RegistryObject<Item> NH_AMETHYST_SWORD = REGISTRY.register("nh_amethyst_sword", () -> new NHAmethystSwordItem());
	public static final RegistryObject<Item> IH_DIAMOND_PICKAXE = REGISTRY.register("ih_diamond_pickaxe", () -> new IHDiamondPickaxeItem());
	public static final RegistryObject<Item> SH_DIAMOND_PICKAXE = REGISTRY.register("sh_diamond_pickaxe", () -> new SHDiamondPickaxeItem());
	public static final RegistryObject<Item> GH_DIAMOND_PICKAXE = REGISTRY.register("gh_diamond_pickaxe", () -> new GHDiamondPickaxeItem());
	public static final RegistryObject<Item> AH_DIAMOND_PICKAXE = REGISTRY.register("ah_diamond_pickaxe", () -> new AHDiamondPickaxeItem());
	public static final RegistryObject<Item> DH_DIAMOND_PICKAXE = REGISTRY.register("dh_diamond_pickaxe", () -> new DHDiamondPickaxeItem());
	public static final RegistryObject<Item> EH_DIAMOND_PICKAXE = REGISTRY.register("eh_diamond_pickaxe", () -> new EHDiamondPickaxeItem());
	public static final RegistryObject<Item> CH_DIAMOND_PICKAXE = REGISTRY.register("ch_diamond_pickaxe", () -> new CHDiamondPickaxeItem());
	public static final RegistryObject<Item> NH_DIAMOND_PICKAXE = REGISTRY.register("nh_diamond_pickaxe", () -> new NHDiamondPickaxeItem());
	public static final RegistryObject<Item> IH_DIAMOND_AXE = REGISTRY.register("ih_diamond_axe", () -> new IHDiamondAxeItem());
	public static final RegistryObject<Item> SH_DIAMOND_AXE = REGISTRY.register("sh_diamond_axe", () -> new SHDiamondAxeItem());
	public static final RegistryObject<Item> GH_DIAMOND_AXE = REGISTRY.register("gh_diamond_axe", () -> new GHDiamondAxeItem());
	public static final RegistryObject<Item> AH_DIAMOND_AXE = REGISTRY.register("ah_diamond_axe", () -> new AHDiamondAxeItem());
	public static final RegistryObject<Item> DH_DIAMOND_AXE = REGISTRY.register("dh_diamond_axe", () -> new DHDiamondAxeItem());
	public static final RegistryObject<Item> EH_DIAMOND_AXE = REGISTRY.register("eh_diamond_axe", () -> new EHDiamondAxeItem());
	public static final RegistryObject<Item> CH_DIAMOND_AXE = REGISTRY.register("ch_diamond_axe", () -> new CHDiamondAxeItem());
	public static final RegistryObject<Item> NH_DIAMOND_AXE = REGISTRY.register("nh_diamond_axe", () -> new NHDiamondAxeItem());
	public static final RegistryObject<Item> IH_DIAMOND_SHOVEL = REGISTRY.register("ih_diamond_shovel", () -> new IHDiamondShovelItem());
	public static final RegistryObject<Item> SH_DIAMOND_SHOVEL = REGISTRY.register("sh_diamond_shovel", () -> new SHDiamondShovelItem());
	public static final RegistryObject<Item> GH_DIAMOND_SHOVEL = REGISTRY.register("gh_diamond_shovel", () -> new GHDiamondShovelItem());
	public static final RegistryObject<Item> AH_DIAMOND_SHOVEL = REGISTRY.register("ah_diamond_shovel", () -> new AHDiamondShovelItem());
	public static final RegistryObject<Item> DH_DIAMOND_SHOVEL = REGISTRY.register("dh_diamond_shovel", () -> new DHDiamondShovelItem());
	public static final RegistryObject<Item> EH_DIAMOND_SHOVEL = REGISTRY.register("eh_diamond_shovel", () -> new EHDiamondShovelItem());
	public static final RegistryObject<Item> CH_DIAMOND_SHOVEL = REGISTRY.register("ch_diamond_shovel", () -> new CHDiamondShovelItem());
	public static final RegistryObject<Item> NH_DIAMOND_SHOVEL = REGISTRY.register("nh_diamond_shovel", () -> new NHDiamondShovelItem());
	public static final RegistryObject<Item> IH_DIAMOND_HOE = REGISTRY.register("ih_diamond_hoe", () -> new IHDiamondHoeItem());
	public static final RegistryObject<Item> SH_DIAMOND_HOE = REGISTRY.register("sh_diamond_hoe", () -> new SHDiamondHoeItem());
	public static final RegistryObject<Item> GH_DIAMOND_HOE = REGISTRY.register("gh_diamond_hoe", () -> new GHDiamondHoeItem());
	public static final RegistryObject<Item> AH_DIAMOND_HOE = REGISTRY.register("ah_diamond_hoe", () -> new AHDiamondHoeItem());
	public static final RegistryObject<Item> DH_DIAMOND_HOE = REGISTRY.register("dh_diamond_hoe", () -> new DHDiamondHoeItem());
	public static final RegistryObject<Item> EH_DIAMOND_HOE = REGISTRY.register("eh_diamond_hoe", () -> new EHDiamondHoeItem());
	public static final RegistryObject<Item> CH_DIAMOND_HOE = REGISTRY.register("ch_diamond_hoe", () -> new CHDiamondHoeItem());
	public static final RegistryObject<Item> NH_DIAMOND_HOE = REGISTRY.register("nh_diamond_hoe", () -> new NHDiamondHoeItem());
	public static final RegistryObject<Item> IH_DIAMOND_SWORD = REGISTRY.register("ih_diamond_sword", () -> new IHDiamondSwordItem());
	public static final RegistryObject<Item> SH_DIAMOND_SWORD = REGISTRY.register("sh_diamond_sword", () -> new SHDiamondSwordItem());
	public static final RegistryObject<Item> GH_DIAMOND_SWORD = REGISTRY.register("gh_diamond_sword", () -> new GHDiamondSwordItem());
	public static final RegistryObject<Item> AH_DIAMOND_SWORD = REGISTRY.register("ah_diamond_sword", () -> new AHDiamondSwordItem());
	public static final RegistryObject<Item> DH_DIAMOND_SWORD = REGISTRY.register("dh_diamond_sword", () -> new DHDiamondSwordItem());
	public static final RegistryObject<Item> EH_DIAMOND_SWORD = REGISTRY.register("eh_diamond_sword", () -> new EHDiamondSwordItem());
	public static final RegistryObject<Item> CH_DIAMOND_SWORD = REGISTRY.register("ch_diamond_sword", () -> new CHDiamondSwordItem());
	public static final RegistryObject<Item> NH_DIAMOND_SWORD = REGISTRY.register("nh_diamond_sword", () -> new NHDiamondSwordItem());
	public static final RegistryObject<Item> IH_EMERALD_PICKAXE = REGISTRY.register("ih_emerald_pickaxe", () -> new IHEmeraldPickaxeItem());
	public static final RegistryObject<Item> SH_EMERALD_PICKAXE = REGISTRY.register("sh_emerald_pickaxe", () -> new SHEmeraldPickaxeItem());
	public static final RegistryObject<Item> GH_EMERALD_PICKAXE = REGISTRY.register("gh_emerald_pickaxe", () -> new GHEmeraldPickaxeItem());
	public static final RegistryObject<Item> AH_EMERALD_PICKAXE = REGISTRY.register("ah_emerald_pickaxe", () -> new AHEmeraldPickaxeItem());
	public static final RegistryObject<Item> DH_EMERALD_PICKAXE = REGISTRY.register("dh_emerald_pickaxe", () -> new DHEmeraldPickaxeItem());
	public static final RegistryObject<Item> EH_EMERALD_PICKAXE = REGISTRY.register("eh_emerald_pickaxe", () -> new EHEmeraldPickaxeItem());
	public static final RegistryObject<Item> CH_EMERALD_PICKAXE = REGISTRY.register("ch_emerald_pickaxe", () -> new CHEmeraldPickaxeItem());
	public static final RegistryObject<Item> NH_EMERALD_PICKAXE = REGISTRY.register("nh_emerald_pickaxe", () -> new NHEmeraldPickaxeItem());
	public static final RegistryObject<Item> IH_EMERALD_AXE = REGISTRY.register("ih_emerald_axe", () -> new IHEmeraldAxeItem());
	public static final RegistryObject<Item> SH_EMERALD_AXE = REGISTRY.register("sh_emerald_axe", () -> new SHEmeraldAxeItem());
	public static final RegistryObject<Item> GH_EMERALD_AXE = REGISTRY.register("gh_emerald_axe", () -> new GHEmeraldAxeItem());
	public static final RegistryObject<Item> AH_EMERALD_AXE = REGISTRY.register("ah_emerald_axe", () -> new AHEmeraldAxeItem());
	public static final RegistryObject<Item> DH_EMERALD_AXE = REGISTRY.register("dh_emerald_axe", () -> new DHEmeraldAxeItem());
	public static final RegistryObject<Item> EH_EMERALD_AXE = REGISTRY.register("eh_emerald_axe", () -> new EHEmeraldAxeItem());
	public static final RegistryObject<Item> CH_EMERALD_AXE = REGISTRY.register("ch_emerald_axe", () -> new CHEmeraldAxeItem());
	public static final RegistryObject<Item> NH_EMERALD_AXE = REGISTRY.register("nh_emerald_axe", () -> new NHEmeraldAxeItem());
	public static final RegistryObject<Item> IH_EMERALD_SHOVEL = REGISTRY.register("ih_emerald_shovel", () -> new IHEmeraldShovelItem());
	public static final RegistryObject<Item> SH_EMERALD_SHOVEL = REGISTRY.register("sh_emerald_shovel", () -> new SHEmeraldShovelItem());
	public static final RegistryObject<Item> GH_EMERALD_SHOVEL = REGISTRY.register("gh_emerald_shovel", () -> new GHEmeraldShovelItem());
	public static final RegistryObject<Item> AH_EMERALD_SHOVEL = REGISTRY.register("ah_emerald_shovel", () -> new AHEmeraldShovelItem());
	public static final RegistryObject<Item> DH_EMERALD_SHOVEL = REGISTRY.register("dh_emerald_shovel", () -> new DHEmeraldShovelItem());
	public static final RegistryObject<Item> EH_EMERALD_SHOVEL = REGISTRY.register("eh_emerald_shovel", () -> new EHEmeraldShovelItem());
	public static final RegistryObject<Item> CH_EMERALD_SHOVEL = REGISTRY.register("ch_emerald_shovel", () -> new CHEmeraldShovelItem());
	public static final RegistryObject<Item> NH_EMERALD_SHOVEL = REGISTRY.register("nh_emerald_shovel", () -> new NHEmeraldShovelItem());
	public static final RegistryObject<Item> IH_EMERALD_HOE = REGISTRY.register("ih_emerald_hoe", () -> new IHEmeraldHoeItem());
	public static final RegistryObject<Item> SH_EMERALD_HOE = REGISTRY.register("sh_emerald_hoe", () -> new SHEmeraldHoeItem());
	public static final RegistryObject<Item> GH_EMERALD_HOE = REGISTRY.register("gh_emerald_hoe", () -> new GHEmeraldHoeItem());
	public static final RegistryObject<Item> AH_EMERALD_HOE = REGISTRY.register("ah_emerald_hoe", () -> new AHEmeraldHoeItem());
	public static final RegistryObject<Item> DH_EMERALD_HOE = REGISTRY.register("dh_emerald_hoe", () -> new DHEmeraldHoeItem());
	public static final RegistryObject<Item> EH_EMERALD_HOE = REGISTRY.register("eh_emerald_hoe", () -> new EHEmeraldHoeItem());
	public static final RegistryObject<Item> CH_EMERALD_HOE = REGISTRY.register("ch_emerald_hoe", () -> new CHEmeraldHoeItem());
	public static final RegistryObject<Item> NH_EMERALD_HOE = REGISTRY.register("nh_emerald_hoe", () -> new NHEmeraldHoeItem());
	public static final RegistryObject<Item> IH_EMERALD_SWORD = REGISTRY.register("ih_emerald_sword", () -> new IHEmeraldSwordItem());
	public static final RegistryObject<Item> SH_EMERALD_SWORD = REGISTRY.register("sh_emerald_sword", () -> new SHEmeraldSwordItem());
	public static final RegistryObject<Item> GH_EMERALD_SWORD = REGISTRY.register("gh_emerald_sword", () -> new GHEmeraldSwordItem());
	public static final RegistryObject<Item> AH_EMERALD_SWORD = REGISTRY.register("ah_emerald_sword", () -> new AHEmeraldSwordItem());
	public static final RegistryObject<Item> DH_EMERALD_SWORD = REGISTRY.register("dh_emerald_sword", () -> new DHEmeraldSwordItem());
	public static final RegistryObject<Item> EH_EMERALD_SWORD = REGISTRY.register("eh_emerald_sword", () -> new EHEmeraldSwordItem());
	public static final RegistryObject<Item> CH_EMERALD_SWORD = REGISTRY.register("ch_emerald_sword", () -> new CHEmeraldSwordItem());
	public static final RegistryObject<Item> NH_EMERALD_SWORD = REGISTRY.register("nh_emerald_sword", () -> new NHEmeraldSwordItem());
	public static final RegistryObject<Item> IH_COPPER_PICKAXE = REGISTRY.register("ih_copper_pickaxe", () -> new IHCopperPickaxeItem());
	public static final RegistryObject<Item> SH_COPPER_PICKAXE = REGISTRY.register("sh_copper_pickaxe", () -> new SHCopperPickaxeItem());
	public static final RegistryObject<Item> GH_COPPER_PICKAXE = REGISTRY.register("gh_copper_pickaxe", () -> new GHCopperPickaxeItem());
	public static final RegistryObject<Item> AH_COPPER_PICKAXE = REGISTRY.register("ah_copper_pickaxe", () -> new AHCopperPickaxeItem());
	public static final RegistryObject<Item> DH_COPPER_PICKAXE = REGISTRY.register("dh_copper_pickaxe", () -> new DHCopperPickaxeItem());
	public static final RegistryObject<Item> EH_COPPER_PICKAXE = REGISTRY.register("eh_copper_pickaxe", () -> new EHCopperPickaxeItem());
	public static final RegistryObject<Item> CH_COPPER_PICKAXE = REGISTRY.register("ch_copper_pickaxe", () -> new CHCopperPickaxeItem());
	public static final RegistryObject<Item> NH_COPPER_PICKAXE = REGISTRY.register("nh_copper_pickaxe", () -> new NHCopperPickaxeItem());
	public static final RegistryObject<Item> IH_COPPER_AXE = REGISTRY.register("ih_copper_axe", () -> new IHCopperAxeItem());
	public static final RegistryObject<Item> SH_COPPER_AXE = REGISTRY.register("sh_copper_axe", () -> new SHCopperAxeItem());
	public static final RegistryObject<Item> GH_COPPER_AXE = REGISTRY.register("gh_copper_axe", () -> new GHCopperAxeItem());
	public static final RegistryObject<Item> AH_COPPER_AXE = REGISTRY.register("ah_copper_axe", () -> new AHCopperAxeItem());
	public static final RegistryObject<Item> DH_COPPER_AXE = REGISTRY.register("dh_copper_axe", () -> new DHCopperAxeItem());
	public static final RegistryObject<Item> EH_COPPER_AXE = REGISTRY.register("eh_copper_axe", () -> new EHCopperAxeItem());
	public static final RegistryObject<Item> CH_COPPER_AXE = REGISTRY.register("ch_copper_axe", () -> new CHCopperAxeItem());
	public static final RegistryObject<Item> NH_COPPER_AXE = REGISTRY.register("nh_copper_axe", () -> new NHCopperAxeItem());
	public static final RegistryObject<Item> IH_COPPER_SHOVEL = REGISTRY.register("ih_copper_shovel", () -> new IHCopperShovelItem());
	public static final RegistryObject<Item> SH_COPPER_SHOVEL = REGISTRY.register("sh_copper_shovel", () -> new SHCopperShovelItem());
	public static final RegistryObject<Item> GH_COPPER_SHOVEL = REGISTRY.register("gh_copper_shovel", () -> new GHCopperShovelItem());
	public static final RegistryObject<Item> AH_COPPER_SHOVEL = REGISTRY.register("ah_copper_shovel", () -> new AHCopperShovelItem());
	public static final RegistryObject<Item> DH_COPPER_SHOVEL = REGISTRY.register("dh_copper_shovel", () -> new DHCopperShovelItem());
	public static final RegistryObject<Item> EH_COPPER_SHOVEL = REGISTRY.register("eh_copper_shovel", () -> new EHCopperShovelItem());
	public static final RegistryObject<Item> CH_COPPER_SHOVEL = REGISTRY.register("ch_copper_shovel", () -> new CHCopperShovelItem());
	public static final RegistryObject<Item> NH_COPPER_SHOVEL = REGISTRY.register("nh_copper_shovel", () -> new NHCopperShovelItem());
	public static final RegistryObject<Item> IH_COPPER_HOE = REGISTRY.register("ih_copper_hoe", () -> new IHCopperHoeItem());
	public static final RegistryObject<Item> SH_COPPER_HOE = REGISTRY.register("sh_copper_hoe", () -> new SHCopperHoeItem());
	public static final RegistryObject<Item> GH_COPPER_HOE = REGISTRY.register("gh_copper_hoe", () -> new GHCopperHoeItem());
	public static final RegistryObject<Item> AH_COPPER_HOE = REGISTRY.register("ah_copper_hoe", () -> new AHCopperHoeItem());
	public static final RegistryObject<Item> DH_COPPER_HOE = REGISTRY.register("dh_copper_hoe", () -> new DHCopperHoeItem());
	public static final RegistryObject<Item> EH_COPPER_HOE = REGISTRY.register("eh_copper_hoe", () -> new EHCopperHoeItem());
	public static final RegistryObject<Item> CH_COPPER_HOE = REGISTRY.register("ch_copper_hoe", () -> new CHCopperHoeItem());
	public static final RegistryObject<Item> NH_COPPER_HOE = REGISTRY.register("nh_copper_hoe", () -> new NHCopperHoeItem());
	public static final RegistryObject<Item> IH_COPPER_SWORD = REGISTRY.register("ih_copper_sword", () -> new IHCopperSwordItem());
	public static final RegistryObject<Item> SH_COPPER_SWORD = REGISTRY.register("sh_copper_sword", () -> new SHCopperSwordItem());
	public static final RegistryObject<Item> GH_COPPER_SWORD = REGISTRY.register("gh_copper_sword", () -> new GHCopperSwordItem());
	public static final RegistryObject<Item> AH_COPPER_SWORD = REGISTRY.register("ah_copper_sword", () -> new AHCopperSwordItem());
	public static final RegistryObject<Item> DH_COPPER_SWORD = REGISTRY.register("dh_copper_sword", () -> new DHCopperSwordItem());
	public static final RegistryObject<Item> EH_COPPER_SWORD = REGISTRY.register("eh_copper_sword", () -> new EHCopperSwordItem());
	public static final RegistryObject<Item> CH_COPPER_SWORD = REGISTRY.register("ch_copper_sword", () -> new CHCopperSwordItem());
	public static final RegistryObject<Item> NH_COPPER_SWORD = REGISTRY.register("nh_copper_sword", () -> new NHCopperSwordItem());
	public static final RegistryObject<Item> IH_NETHERITE_PICKAXE = REGISTRY.register("ih_netherite_pickaxe", () -> new IHNetheritePickaxeItem());
	public static final RegistryObject<Item> SH_NETHERITE_PICKAXE = REGISTRY.register("sh_netherite_pickaxe", () -> new SHNetheritePickaxeItem());
	public static final RegistryObject<Item> GH_NETHERITE_PICKAXE = REGISTRY.register("gh_netherite_pickaxe", () -> new GHNetheritePickaxeItem());
	public static final RegistryObject<Item> AH_NETHERITE_PICKAXE = REGISTRY.register("ah_netherite_pickaxe", () -> new AHNetheritePickaxeItem());
	public static final RegistryObject<Item> DH_NETHERITE_PICKAXE = REGISTRY.register("dh_netherite_pickaxe", () -> new DHNetheritePickaxeItem());
	public static final RegistryObject<Item> EH_NETHERITE_PICKAXE = REGISTRY.register("eh_netherite_pickaxe", () -> new EHNetheritePickaxeItem());
	public static final RegistryObject<Item> CH_NETHERITE_PICKAXE = REGISTRY.register("ch_netherite_pickaxe", () -> new CHNetheritePickaxeItem());
	public static final RegistryObject<Item> NH_NETHERITE_PICKAXE = REGISTRY.register("nh_netherite_pickaxe", () -> new NHNetheritePickaxeItem());
	public static final RegistryObject<Item> IH_NETHERITE_AXE = REGISTRY.register("ih_netherite_axe", () -> new IHNetheriteAxeItem());
	public static final RegistryObject<Item> SH_NETHERITE_AXE = REGISTRY.register("sh_netherite_axe", () -> new SHNetheriteAxeItem());
	public static final RegistryObject<Item> GH_NETHERITE_AXE = REGISTRY.register("gh_netherite_axe", () -> new GHNetheriteAxeItem());
	public static final RegistryObject<Item> AH_NETHERITE_AXE = REGISTRY.register("ah_netherite_axe", () -> new AHNetheriteAxeItem());
	public static final RegistryObject<Item> DH_NETHERITE_AXE = REGISTRY.register("dh_netherite_axe", () -> new DHNetheriteAxeItem());
	public static final RegistryObject<Item> EH_NETHERITE_AXE = REGISTRY.register("eh_netherite_axe", () -> new EHNetheriteAxeItem());
	public static final RegistryObject<Item> CH_NETHERITE_AXE = REGISTRY.register("ch_netherite_axe", () -> new CHNetheriteAxeItem());
	public static final RegistryObject<Item> NH_NETHERITE_AXE = REGISTRY.register("nh_netherite_axe", () -> new NHNetheriteAxeItem());
	public static final RegistryObject<Item> IH_NETHERITE_SHOVEL = REGISTRY.register("ih_netherite_shovel", () -> new IHNetheriteShovelItem());
	public static final RegistryObject<Item> SH_NETHERITE_SHOVEL = REGISTRY.register("sh_netherite_shovel", () -> new SHNetheriteShovelItem());
	public static final RegistryObject<Item> GH_NETHERITE_SHOVEL = REGISTRY.register("gh_netherite_shovel", () -> new GHNetheriteShovelItem());
	public static final RegistryObject<Item> AH_NETHERITE_SHOVEL = REGISTRY.register("ah_netherite_shovel", () -> new AHNetheriteShovelItem());
	public static final RegistryObject<Item> DH_NETHERITE_SHOVEL = REGISTRY.register("dh_netherite_shovel", () -> new DHNetheriteShovelItem());
	public static final RegistryObject<Item> EH_NETHERITE_SHOVEL = REGISTRY.register("eh_netherite_shovel", () -> new EHNetheriteShovelItem());
	public static final RegistryObject<Item> CH_NETHERITE_SHOVEL = REGISTRY.register("ch_netherite_shovel", () -> new CHNetheriteShovelItem());
	public static final RegistryObject<Item> NH_NETHERITE_SHOVEL = REGISTRY.register("nh_netherite_shovel", () -> new NHNetheriteShovelItem());
	public static final RegistryObject<Item> IH_NETHERITE_HOE = REGISTRY.register("ih_netherite_hoe", () -> new IHNetheriteHoeItem());
	public static final RegistryObject<Item> SH_NETHERITE_HOE = REGISTRY.register("sh_netherite_hoe", () -> new SHNetheriteHoeItem());
	public static final RegistryObject<Item> GH_NETHERITE_HOE = REGISTRY.register("gh_netherite_hoe", () -> new GHNetheriteHoeItem());
	public static final RegistryObject<Item> AH_NETHERITE_HOE = REGISTRY.register("ah_netherite_hoe", () -> new AHNetheriteHoeItem());
	public static final RegistryObject<Item> DH_NETHERITE_HOE = REGISTRY.register("dh_netherite_hoe", () -> new DHNetheriteHoeItem());
	public static final RegistryObject<Item> EH_NETHERITE_HOE = REGISTRY.register("eh_netherite_hoe", () -> new EHNetheriteHoeItem());
	public static final RegistryObject<Item> CH_NETHERITE_HOE = REGISTRY.register("ch_netherite_hoe", () -> new CHNetheriteHoeItem());
	public static final RegistryObject<Item> NH_NETHERITE_HOE = REGISTRY.register("nh_netherite_hoe", () -> new NHNetheriteHoeItem());
	public static final RegistryObject<Item> IH_NETHERITE_SWORD = REGISTRY.register("ih_netherite_sword", () -> new IHNetheriteSwordItem());
	public static final RegistryObject<Item> SH_NETHERITE_SWORD = REGISTRY.register("sh_netherite_sword", () -> new SHNetheriteSwordItem());
	public static final RegistryObject<Item> GH_NETHERITE_SWORD = REGISTRY.register("gh_netherite_sword", () -> new GHNetheriteSwordItem());
	public static final RegistryObject<Item> AH_NETHERITE_SWORD = REGISTRY.register("ah_netherite_sword", () -> new AHNetheriteSwordItem());
	public static final RegistryObject<Item> DH_NETHERITE_SWORD = REGISTRY.register("dh_netherite_sword", () -> new DHNetheriteSwordItem());
	public static final RegistryObject<Item> EH_NETHERITE_SWORD = REGISTRY.register("eh_netherite_sword", () -> new EHNetheriteSwordItem());
	public static final RegistryObject<Item> CH_NETHERITE_SWORD = REGISTRY.register("ch_netherite_sword", () -> new CHNetheriteSwordItem());
	public static final RegistryObject<Item> NH_NETHERITE_SWORD = REGISTRY.register("nh_netherite_sword", () -> new NHNetheriteSwordItem());
}
