
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.multipiecetools.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.multipiecetools.item.StoneSwordHandleItem;
import net.mcreator.multipiecetools.item.StoneSwordBladeItem;
import net.mcreator.multipiecetools.item.StoneShovelHeadItem;
import net.mcreator.multipiecetools.item.StonePickaxeHeadItem;
import net.mcreator.multipiecetools.item.StoneHoeHeadItem;
import net.mcreator.multipiecetools.item.StoneHandleItem;
import net.mcreator.multipiecetools.item.StoneAxeHeadItem;
import net.mcreator.multipiecetools.item.NetheriteSwordHandleItem;
import net.mcreator.multipiecetools.item.NetheriteSwordBladeItem;
import net.mcreator.multipiecetools.item.NetheriteShovelHeadItem;
import net.mcreator.multipiecetools.item.NetheritePickaxeHeadItem;
import net.mcreator.multipiecetools.item.NetheriteHoeHeadItem;
import net.mcreator.multipiecetools.item.NetheriteHandleItem;
import net.mcreator.multipiecetools.item.NetheriteAxeHeadItem;
import net.mcreator.multipiecetools.item.IronSwordHandleItem;
import net.mcreator.multipiecetools.item.IronSwordBladeItem;
import net.mcreator.multipiecetools.item.IronShovelHeadItem;
import net.mcreator.multipiecetools.item.IronPickaxeHeadItem;
import net.mcreator.multipiecetools.item.IronHoeHeadItem;
import net.mcreator.multipiecetools.item.IronHandleItem;
import net.mcreator.multipiecetools.item.IronAxeHeadItem;
import net.mcreator.multipiecetools.item.GoldSwordHandleItem;
import net.mcreator.multipiecetools.item.GoldSwordBladeItem;
import net.mcreator.multipiecetools.item.GoldShovelHeadItem;
import net.mcreator.multipiecetools.item.GoldPickaxeHeadItem;
import net.mcreator.multipiecetools.item.GoldHoeHeadItem;
import net.mcreator.multipiecetools.item.GoldHandleItem;
import net.mcreator.multipiecetools.item.GoldAxeHeadItem;
import net.mcreator.multipiecetools.item.EmeraldSwordHandleItem;
import net.mcreator.multipiecetools.item.EmeraldSwordBladeItem;
import net.mcreator.multipiecetools.item.EmeraldShovelHeadItem;
import net.mcreator.multipiecetools.item.EmeraldPickaxeHeadItem;
import net.mcreator.multipiecetools.item.EmeraldHoeHeadItem;
import net.mcreator.multipiecetools.item.EmeraldHandleItem;
import net.mcreator.multipiecetools.item.EmeraldAxeHeadItem;
import net.mcreator.multipiecetools.item.DiamondSwordHandleItem;
import net.mcreator.multipiecetools.item.DiamondSwordBladeItem;
import net.mcreator.multipiecetools.item.DiamondShovelHeadItem;
import net.mcreator.multipiecetools.item.DiamondPickaxeHeadItem;
import net.mcreator.multipiecetools.item.DiamondHoeHeadItem;
import net.mcreator.multipiecetools.item.DiamondHandleItem;
import net.mcreator.multipiecetools.item.DiamondAxeHeadItem;
import net.mcreator.multipiecetools.item.CopperSwordHandleItem;
import net.mcreator.multipiecetools.item.CopperSwordBladeItem;
import net.mcreator.multipiecetools.item.CopperShovelHeadItem;
import net.mcreator.multipiecetools.item.CopperPickaxeHeadItem;
import net.mcreator.multipiecetools.item.CopperHoeHeadItem;
import net.mcreator.multipiecetools.item.CopperHandleItem;
import net.mcreator.multipiecetools.item.CopperAxeHeadItem;
import net.mcreator.multipiecetools.item.AmethystSwordHandleItem;
import net.mcreator.multipiecetools.item.AmethystSwordBladeItem;
import net.mcreator.multipiecetools.item.AmethystShovelHeadItem;
import net.mcreator.multipiecetools.item.AmethystPickaxeHeadItem;
import net.mcreator.multipiecetools.item.AmethystHoeHeadItem;
import net.mcreator.multipiecetools.item.AmethystHandleItem;
import net.mcreator.multipiecetools.item.AmethystAxeHeadItem;
import net.mcreator.multipiecetools.MultiPieceToolsMod;

public class MultiPieceToolsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MultiPieceToolsMod.MODID);
	public static final RegistryObject<Item> STONE_HANDLE = REGISTRY.register("stone_handle", () -> new StoneHandleItem());
	public static final RegistryObject<Item> IRON_HANDLE = REGISTRY.register("iron_handle", () -> new IronHandleItem());
	public static final RegistryObject<Item> GOLD_HANDLE = REGISTRY.register("gold_handle", () -> new GoldHandleItem());
	public static final RegistryObject<Item> AMETHYST_HANDLE = REGISTRY.register("amethyst_handle", () -> new AmethystHandleItem());
	public static final RegistryObject<Item> DIAMOND_HANDLE = REGISTRY.register("diamond_handle", () -> new DiamondHandleItem());
	public static final RegistryObject<Item> EMERALD_HANDLE = REGISTRY.register("emerald_handle", () -> new EmeraldHandleItem());
	public static final RegistryObject<Item> COPPER_HANDLE = REGISTRY.register("copper_handle", () -> new CopperHandleItem());
	public static final RegistryObject<Item> NETHERITE_HANDLE = REGISTRY.register("netherite_handle", () -> new NetheriteHandleItem());
	public static final RegistryObject<Item> IRON_PICKAXE_HEAD = REGISTRY.register("iron_pickaxe_head", () -> new IronPickaxeHeadItem());
	public static final RegistryObject<Item> STONE_PICKAXE_HEAD = REGISTRY.register("stone_pickaxe_head", () -> new StonePickaxeHeadItem());
	public static final RegistryObject<Item> GOLD_PICKAXE_HEAD = REGISTRY.register("gold_pickaxe_head", () -> new GoldPickaxeHeadItem());
	public static final RegistryObject<Item> AMETHYST_PICKAXE_HEAD = REGISTRY.register("amethyst_pickaxe_head", () -> new AmethystPickaxeHeadItem());
	public static final RegistryObject<Item> DIAMOND_PICKAXE_HEAD = REGISTRY.register("diamond_pickaxe_head", () -> new DiamondPickaxeHeadItem());
	public static final RegistryObject<Item> EMERALD_PICKAXE_HEAD = REGISTRY.register("emerald_pickaxe_head", () -> new EmeraldPickaxeHeadItem());
	public static final RegistryObject<Item> COPPER_PICKAXE_HEAD = REGISTRY.register("copper_pickaxe_head", () -> new CopperPickaxeHeadItem());
	public static final RegistryObject<Item> NETHERITE_PICKAXE_HEAD = REGISTRY.register("netherite_pickaxe_head", () -> new NetheritePickaxeHeadItem());
	public static final RegistryObject<Item> IRON_AXE_HEAD = REGISTRY.register("iron_axe_head", () -> new IronAxeHeadItem());
	public static final RegistryObject<Item> STONE_AXE_HEAD = REGISTRY.register("stone_axe_head", () -> new StoneAxeHeadItem());
	public static final RegistryObject<Item> GOLD_AXE_HEAD = REGISTRY.register("gold_axe_head", () -> new GoldAxeHeadItem());
	public static final RegistryObject<Item> AMETHYST_AXE_HEAD = REGISTRY.register("amethyst_axe_head", () -> new AmethystAxeHeadItem());
	public static final RegistryObject<Item> DIAMOND_AXE_HEAD = REGISTRY.register("diamond_axe_head", () -> new DiamondAxeHeadItem());
	public static final RegistryObject<Item> EMERALD_AXE_HEAD = REGISTRY.register("emerald_axe_head", () -> new EmeraldAxeHeadItem());
	public static final RegistryObject<Item> COPPER_AXE_HEAD = REGISTRY.register("copper_axe_head", () -> new CopperAxeHeadItem());
	public static final RegistryObject<Item> NETHERITE_AXE_HEAD = REGISTRY.register("netherite_axe_head", () -> new NetheriteAxeHeadItem());
	public static final RegistryObject<Item> IRON_SHOVEL_HEAD = REGISTRY.register("iron_shovel_head", () -> new IronShovelHeadItem());
	public static final RegistryObject<Item> STONE_SHOVEL_HEAD = REGISTRY.register("stone_shovel_head", () -> new StoneShovelHeadItem());
	public static final RegistryObject<Item> GOLD_SHOVEL_HEAD = REGISTRY.register("gold_shovel_head", () -> new GoldShovelHeadItem());
	public static final RegistryObject<Item> AMETHYST_SHOVEL_HEAD = REGISTRY.register("amethyst_shovel_head", () -> new AmethystShovelHeadItem());
	public static final RegistryObject<Item> DIAMOND_SHOVEL_HEAD = REGISTRY.register("diamond_shovel_head", () -> new DiamondShovelHeadItem());
	public static final RegistryObject<Item> EMERALD_SHOVEL_HEAD = REGISTRY.register("emerald_shovel_head", () -> new EmeraldShovelHeadItem());
	public static final RegistryObject<Item> COPPER_SHOVEL_HEAD = REGISTRY.register("copper_shovel_head", () -> new CopperShovelHeadItem());
	public static final RegistryObject<Item> NETHERITE_SHOVEL_HEAD = REGISTRY.register("netherite_shovel_head", () -> new NetheriteShovelHeadItem());
	public static final RegistryObject<Item> IRON_HOE_HEAD = REGISTRY.register("iron_hoe_head", () -> new IronHoeHeadItem());
	public static final RegistryObject<Item> STONE_HOE_HEAD = REGISTRY.register("stone_hoe_head", () -> new StoneHoeHeadItem());
	public static final RegistryObject<Item> GOLD_HOE_HEAD = REGISTRY.register("gold_hoe_head", () -> new GoldHoeHeadItem());
	public static final RegistryObject<Item> AMETHYST_HOE_HEAD = REGISTRY.register("amethyst_hoe_head", () -> new AmethystHoeHeadItem());
	public static final RegistryObject<Item> DIAMOND_HOE_HEAD = REGISTRY.register("diamond_hoe_head", () -> new DiamondHoeHeadItem());
	public static final RegistryObject<Item> EMERALD_HOE_HEAD = REGISTRY.register("emerald_hoe_head", () -> new EmeraldHoeHeadItem());
	public static final RegistryObject<Item> COPPER_HOE_HEAD = REGISTRY.register("copper_hoe_head", () -> new CopperHoeHeadItem());
	public static final RegistryObject<Item> NETHERITE_HOE_HEAD = REGISTRY.register("netherite_hoe_head", () -> new NetheriteHoeHeadItem());
	public static final RegistryObject<Item> IRON_SWORD_BLADE = REGISTRY.register("iron_sword_blade", () -> new IronSwordBladeItem());
	public static final RegistryObject<Item> STONE_SWORD_BLADE = REGISTRY.register("stone_sword_blade", () -> new StoneSwordBladeItem());
	public static final RegistryObject<Item> GOLD_SWORD_BLADE = REGISTRY.register("gold_sword_blade", () -> new GoldSwordBladeItem());
	public static final RegistryObject<Item> AMETHYST_SWORD_BLADE = REGISTRY.register("amethyst_sword_blade", () -> new AmethystSwordBladeItem());
	public static final RegistryObject<Item> DIAMOND_SWORD_BLADE = REGISTRY.register("diamond_sword_blade", () -> new DiamondSwordBladeItem());
	public static final RegistryObject<Item> EMERALD_SWORD_BLADE = REGISTRY.register("emerald_sword_blade", () -> new EmeraldSwordBladeItem());
	public static final RegistryObject<Item> COPPER_SWORD_BLADE = REGISTRY.register("copper_sword_blade", () -> new CopperSwordBladeItem());
	public static final RegistryObject<Item> NETHERITE_SWORD_BLADE = REGISTRY.register("netherite_sword_blade", () -> new NetheriteSwordBladeItem());
	public static final RegistryObject<Item> IRON_SWORD_HANDLE = REGISTRY.register("iron_sword_handle", () -> new IronSwordHandleItem());
	public static final RegistryObject<Item> STONE_SWORD_HANDLE = REGISTRY.register("stone_sword_handle", () -> new StoneSwordHandleItem());
	public static final RegistryObject<Item> GOLD_SWORD_HANDLE = REGISTRY.register("gold_sword_handle", () -> new GoldSwordHandleItem());
	public static final RegistryObject<Item> AMETHYST_SWORD_HANDLE = REGISTRY.register("amethyst_sword_handle", () -> new AmethystSwordHandleItem());
	public static final RegistryObject<Item> DIAMOND_SWORD_HANDLE = REGISTRY.register("diamond_sword_handle", () -> new DiamondSwordHandleItem());
	public static final RegistryObject<Item> EMERALD_SWORD_HANDLE = REGISTRY.register("emerald_sword_handle", () -> new EmeraldSwordHandleItem());
	public static final RegistryObject<Item> COPPER_SWORD_HANDLE = REGISTRY.register("copper_sword_handle", () -> new CopperSwordHandleItem());
	public static final RegistryObject<Item> NETHERITE_SWORD_HANDLE = REGISTRY.register("netherite_sword_handle", () -> new NetheriteSwordHandleItem());
}
